(* generated by dune *)

(** @canonical Ppx_yojson_conv_expander.Attrs *)
module Attrs = Ppx_yojson_conv_expander__Attrs

(** @canonical Ppx_yojson_conv_expander.Label_with_name *)
module Label_with_name = Ppx_yojson_conv_expander__Label_with_name
