opam-version: "2.0"
lib: [
  "_build/install/default/lib/zmq/META"
  "_build/install/default/lib/zmq/deferred/deferred.ml"
    {"deferred/deferred.ml"}
  "_build/install/default/lib/zmq/deferred/socket.ml" {"deferred/socket.ml"}
  "_build/install/default/lib/zmq/deferred/socket.mli"
    {"deferred/socket.mli"}
  "_build/install/default/lib/zmq/deferred/zmq_deferred.a"
    {"deferred/zmq_deferred.a"}
  "_build/install/default/lib/zmq/deferred/zmq_deferred.cma"
    {"deferred/zmq_deferred.cma"}
  "_build/install/default/lib/zmq/deferred/zmq_deferred.cmi"
    {"deferred/zmq_deferred.cmi"}
  "_build/install/default/lib/zmq/deferred/zmq_deferred.cmt"
    {"deferred/zmq_deferred.cmt"}
  "_build/install/default/lib/zmq/deferred/zmq_deferred.cmx"
    {"deferred/zmq_deferred.cmx"}
  "_build/install/default/lib/zmq/deferred/zmq_deferred.cmxa"
    {"deferred/zmq_deferred.cmxa"}
  "_build/install/default/lib/zmq/deferred/zmq_deferred.ml"
    {"deferred/zmq_deferred.ml"}
  "_build/install/default/lib/zmq/deferred/zmq_deferred__Deferred.cmi"
    {"deferred/zmq_deferred__Deferred.cmi"}
  "_build/install/default/lib/zmq/deferred/zmq_deferred__Deferred.cmt"
    {"deferred/zmq_deferred__Deferred.cmt"}
  "_build/install/default/lib/zmq/deferred/zmq_deferred__Deferred.cmx"
    {"deferred/zmq_deferred__Deferred.cmx"}
  "_build/install/default/lib/zmq/deferred/zmq_deferred__Socket.cmi"
    {"deferred/zmq_deferred__Socket.cmi"}
  "_build/install/default/lib/zmq/deferred/zmq_deferred__Socket.cmt"
    {"deferred/zmq_deferred__Socket.cmt"}
  "_build/install/default/lib/zmq/deferred/zmq_deferred__Socket.cmti"
    {"deferred/zmq_deferred__Socket.cmti"}
  "_build/install/default/lib/zmq/deferred/zmq_deferred__Socket.cmx"
    {"deferred/zmq_deferred__Socket.cmx"}
  "_build/install/default/lib/zmq/dune-package"
  "_build/install/default/lib/zmq/libzmq_stubs.a"
  "_build/install/default/lib/zmq/opam"
  "_build/install/default/lib/zmq/zmq.a"
  "_build/install/default/lib/zmq/zmq.cma"
  "_build/install/default/lib/zmq/zmq.cmi"
  "_build/install/default/lib/zmq/zmq.cmt"
  "_build/install/default/lib/zmq/zmq.cmti"
  "_build/install/default/lib/zmq/zmq.cmx"
  "_build/install/default/lib/zmq/zmq.cmxa"
  "_build/install/default/lib/zmq/zmq.ml"
  "_build/install/default/lib/zmq/zmq.mli"
]
stublibs: "_build/install/default/lib/stublibs/dllzmq_stubs.so"
doc: [
  "_build/install/default/doc/zmq/CHANGES.md"
  "_build/install/default/doc/zmq/LICENSE.md"
  "_build/install/default/doc/zmq/README.md"
]
libexec: [
  "_build/install/default/lib/zmq/deferred/zmq_deferred.cmxs"
    {"deferred/zmq_deferred.cmxs"}
  "_build/install/default/lib/zmq/zmq.cmxs"
]
