(* generated by dune *)

(** @canonical Jupyter_comm.Manager *)
module Manager = Jupyter_comm__Manager

(** @canonical Jupyter_comm.Router *)
module Router = Jupyter_comm__Router

(** @canonical Jupyter_comm.Stdin *)
module Stdin = Jupyter_comm__Stdin
